/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed40317f-ec75-4385-9e4e-c10f49e09faa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2hargCzaQ",
    "aws_user_pools_web_client_id": "6nimqetebab8hl7tva10u3ifon",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dta3sxskfzg7hdjvzl3dflf7wq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ibfjiqdyebahtcdoca655gwnq4",
    "aws_user_files_s3_bucket": "amplify120948-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
